### ISSUE TITLE
OS X make error envelopegraph.h

### ISSUE THREAD

**Issue by laerm0** [riban-bw/vzeditor#35]
Hi, thanks for all the work you've put in on this recently. I've just updated for the first time in a while and I have an error after `make vzeditor` (`make clean` had no issues).

```
c++ `wx-config --cxxflags` -Iinclude -O2   -c -o src/vzeditorapp.o src/vzeditorapp.cpp
In file included from src/vzeditorapp.cpp:13:
include/vzeditormain.h:13:10: fatal error: 'envelopegraph.h' file not found
#include "envelopegraph.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/vzeditorapp.o] Error 1
```

**Comment by riban-bw** [comment]
You may need to pull the submodules. I developed the envelope graph widget as a separate project so as to make it reusable. I link it as a git submodule. Try:

``` git pull --recurse-submodules ```

**Comment by laerm0** [comment]
Hmm, same error, sadly. ``git pull  – recurse-submodules` only updated the `README`. Went from `2738998` to `a81ccdc`.

**Comment by riban-bw** [comment]
Sorry - I had missed the fact that you were using makefile and I hadn't updated it. It should work now. Please retest.

**Comment by laerm0** [comment]
Hm, nope. The exact same error as before. Sorry.

**Comment by riban-bw** [comment]
:-( 
Will you check that the file exists? There should be a file called:

```envelopegraph.h```

in directory:

```wxEnvelopeGraph/include```

I will try a build on Linux when I get a chance. (Currently busy with day job!)

**Comment by riban-bw** [comment]
Sorry - my bad!

I have updated the README to detail how to resolve this. If you have already cloned the repository then, from within your local copy run:
```
git submodule update --init
```
If you are cloning from fresh then do so with the command:
```
git clone --recurse-submodules https://github.com/riban-bw/vzeditor.git
```

**Comment by riban-bw** [comment]
I have validated this now works. (I had to fix some other issues so pull the latest commit.) Please retest then close issue if satisfied or add further comment if issues persist.

Cheers

**Comment by laerm0** [comment]
Woo, we've got a build! Thanks very much. :)
